sleep: 1000
version: 0.63.9
exit_on_error: false
workflows:
  foobar:
    description: example placeholder
    args:
      - name: foo
        type: string
      - name: bar
        type: string
        regex: ^bar+\w
        default: bar bdef
        export: barx
    steps:
      - echo hello {current-branch} {foo} world
      - echo goodbye {foo} {barx} cruel world
      - confirm echo {barx} goodbye
      - 'echo "AWS_PROFILE: {AWS_PROFILE}"'
