name: Label issue and pull requests

on:
  pull_request:
    types: opened
    
permissions:
  checks: write
  contents: read
  pull-requests: write
  
jobs:
  label:
    name: Label issue and pull requests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/config/label.yml
          sync-labels: yes
