name: Update README.md with repos categorized by topic
run-name: readme-topics
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: metaory/github-profile-pinned-action@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        with:
          username: metaory
          email: metaory@gmail.com
          repository: git-playground
          topics: |-
            api
            automation
            challenge
            cli
            github-actions
            npm-package
            theme
